import { encodeUtf16LeBase64 } from "./encoding.ts";
import { buildProtectedDirectoryFunctions } from "./protectedDirectoryScript.ts";

export function buildElevatedBootstrapSource(): string {
  return [
    "$ErrorActionPreference = 'Stop'",
    "$selfToken = '__TF_SELF_TOKEN__'",
    "$language = '__TF_LANGUAGE__'",
    "$expectedHash = '__TF_HASH__'",
    "if ($selfToken -cnotmatch '^[A-Za-z0-9+/]+={0,2}$' -or $selfToken.Length -gt 8192) { throw 'Script path token is invalid.' }",
    "if ($language -notin @('ja','en')) { throw 'Display language is invalid.' }",
    "if ($expectedHash -cnotmatch '^[A-Za-z0-9+/]{43}=$') { throw 'Script digest is invalid.' }",
    "$self = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($selfToken))",
    "if ([string]::IsNullOrWhiteSpace($self) -or -not (Test-Path -LiteralPath $self -PathType Leaf)) { throw 'Script path is invalid.' }",
    "function Get-Digest([byte[]]$Bytes) {",
    "  $algorithm = [Security.Cryptography.SHA256]::Create()",
    "  try { return [Convert]::ToBase64String($algorithm.ComputeHash($Bytes)) } finally { $algorithm.Dispose() }",
    "}",
    ...buildProtectedDirectoryFunctions(),
    "$bytes = [IO.File]::ReadAllBytes($self)",
    "if ($bytes.Length -eq 0 -or $bytes.Length -gt 67108864) { throw 'Script size is invalid.' }",
    "if ((Get-Digest $bytes) -cne $expectedHash) { throw 'Script changed during elevation.' }",
    "$text = [Text.Encoding]::UTF8.GetString($bytes)",
    "$lines = [regex]::Split($text, '\\r?\\n')",
    "$start = [Array]::IndexOf($lines, ':RB_TRUSTED_BEGIN')",
    "$end = [Array]::IndexOf($lines, ':RB_TRUSTED_END')",
    "if ($start -lt 0 -or $end -le ($start + 1)) { throw 'Trusted runtime payload is missing.' }",
    "$chunks = @($lines[($start + 1)..($end - 1)] | ForEach-Object { if ($_ -cnotmatch '^:[A-Za-z0-9+/=]{1,1000}$') { throw 'Trusted runtime payload is malformed.' }; $_.Substring(1) })",
    "$trustedBytes = [Convert]::FromBase64String(($chunks -join ''))",
    "if ($trustedBytes.Length -eq 0 -or $trustedBytes.Length -gt 131072) { throw 'Trusted runtime payload size is invalid.' }",
    "$commonData = [Environment]::GetFolderPath([Environment+SpecialFolder]::CommonApplicationData)",
    "if ([string]::IsNullOrWhiteSpace($commonData)) { throw 'ProgramData path is unavailable.' }",
    "$bootstrapBase = Join-Path $commonData 'GamingTweakForgeBootstrap'",
    "$runtimeRoot = Join-Path $bootstrapBase ([Guid]::NewGuid().ToString('N'))",
    "Open-ProtectedDirectory $bootstrapBase",
    "Open-ProtectedDirectory $runtimeRoot",
    "$scriptPath = Join-Path $runtimeRoot 'trusted.ps1'",
    "$trustedSource = [Text.Encoding]::Unicode.GetString($trustedBytes)",
    "[IO.File]::WriteAllText($scriptPath, $trustedSource, [Text.Encoding]::Unicode)",
    "$trustedDigest = Get-Digest ([IO.File]::ReadAllBytes($scriptPath))",
    "$scriptFile = Get-Item -LiteralPath $scriptPath -Force",
    "if (($scriptFile.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) { throw 'Trusted script is a reparse point.' }",
    "$powershell = Join-Path ([Environment]::SystemDirectory) 'WindowsPowerShell\\v1.0\\powershell.exe'",
    "if (-not (Test-Path -LiteralPath $powershell -PathType Leaf)) { throw 'Windows PowerShell was not found in System32.' }",
    "$env:RB_SELF = $self",
    "$env:TF_LANG = $language",
    "$env:TF_SELF_SHA256 = $expectedHash",
    `$quotedScript = '"' + $scriptPath + '"'`,
    "$exitCode = 1",
    "try {",
    "  if ((Get-Digest ([IO.File]::ReadAllBytes($scriptPath))) -cne $trustedDigest) { throw 'Trusted script changed before execution.' }",
    "  $process = Start-Process -FilePath $powershell -ArgumentList @('-NoLogo','-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',$quotedScript) -WorkingDirectory $runtimeRoot -Wait -PassThru",
    "  $exitCode = $process.ExitCode",
    "} finally {",
    "  if (Test-Path -LiteralPath $runtimeRoot) { Remove-Item -LiteralPath $runtimeRoot -Recurse -Force -ErrorAction SilentlyContinue }",
    "}",
    "exit $exitCode",
  ].join("\r\n");
}

export function buildElevatedBootstrapEncodedCommand(): string {
  return encodeUtf16LeBase64(buildElevatedBootstrapSource());
}

export function buildElevationEncodedCommand(): string {
  const source = [
    "$ErrorActionPreference = 'Stop'",
    "$self = $env:RB_SELF",
    "$language = $env:TF_LANG",
    "if ([string]::IsNullOrWhiteSpace($self) -or -not (Test-Path -LiteralPath $self -PathType Leaf)) { throw 'Script path is invalid.' }",
    "if ($language -notin @('ja','en')) { throw 'Display language is invalid.' }",
    "$bytes = [IO.File]::ReadAllBytes($self)",
    "if ($bytes.Length -eq 0 -or $bytes.Length -gt 67108864) { throw 'Script size is invalid.' }",
    "$algorithm = [Security.Cryptography.SHA256]::Create()",
    "try { $digest = [Convert]::ToBase64String($algorithm.ComputeHash($bytes)) } finally { $algorithm.Dispose() }",
    "$text = [Text.Encoding]::UTF8.GetString($bytes)",
    "$lines = [regex]::Split($text, '\\r?\\n')",
    "$start = [Array]::IndexOf($lines, ':RB_ELEVATED_BEGIN')",
    "$end = [Array]::IndexOf($lines, ':RB_ELEVATED_END')",
    "if ($start -lt 0 -or $end -le ($start + 1)) { throw 'Elevation payload is missing.' }",
    "$chunks = @($lines[($start + 1)..($end - 1)] | ForEach-Object { if ($_ -cnotmatch '^:[A-Za-z0-9+/=]{1,1000}$') { throw 'Elevation payload is malformed.' }; $_.Substring(1) })",
    "$bootstrapBytes = [Convert]::FromBase64String(($chunks -join ''))",
    "if ($bootstrapBytes.Length -eq 0 -or $bootstrapBytes.Length -gt 65536) { throw 'Elevation payload size is invalid.' }",
    "$bootstrapSource = [Text.Encoding]::Unicode.GetString($bootstrapBytes)",
    "foreach ($marker in @('__TF_SELF_TOKEN__','__TF_LANGUAGE__','__TF_HASH__')) { if (-not $bootstrapSource.Contains($marker)) { throw ('Elevation marker is missing: ' + $marker) } }",
    "$selfToken = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($self))",
    "$bootstrapSource = $bootstrapSource.Replace('__TF_SELF_TOKEN__', $selfToken).Replace('__TF_LANGUAGE__', $language).Replace('__TF_HASH__', $digest)",
    "$bootstrapCommand = [Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($bootstrapSource))",
    "if ($bootstrapCommand.Length -gt 30000) { throw 'Elevation command is too large.' }",
    "$powershell = Join-Path ([Environment]::SystemDirectory) 'WindowsPowerShell\\v1.0\\powershell.exe'",
    "if (-not (Test-Path -LiteralPath $powershell -PathType Leaf)) { throw 'Windows PowerShell was not found in System32.' }",
    "$process = Start-Process -FilePath $powershell -ArgumentList @('-NoLogo','-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-EncodedCommand',$bootstrapCommand) -Verb RunAs -Wait -PassThru",
    "exit $process.ExitCode",
  ].join(";");
  return encodeUtf16LeBase64(source);
}
