import type { PowerPlanAction } from "../domain/types.ts";

function psString(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

export function buildPowerPlanEntryLiteral(action: PowerPlanAction): string {
  const properties = [
    `Id=${psString(action.id)}`,
    `ActionKind=${psString(action.kind)}`,
    `SchemeGuid=${psString(action.schemeGuid.toLowerCase())}`,
  ];
  return `[pscustomobject]@{${properties.join(";")}}`;
}

export const POWER_PLAN_ENGINE_LINES = [
  "function Assert-PowerPlanState([object]$State, [object]$Entry) {",
  "  if ($null -eq $State) { throw 'Power plan state is empty.' }",
  "  foreach ($property in @('Schema','ProjectId','ActionId','ActionKind','TargetGuid','ActiveGuid')) {",
  "    if ($null -eq $State.PSObject.Properties[$property]) { throw ('Power plan state property is missing: ' + $property) }",
  "  }",
  "  if ($State.Schema -isnot [int] -or $State.Schema -ne 2) { throw 'Unsupported power plan state schema.' }",
  "  foreach ($property in @('ProjectId','ActionId','ActionKind','TargetGuid','ActiveGuid')) { if ($State.$property -isnot [string]) { throw ('Power plan state text property is invalid: ' + $property) } }",
  "  if ($State.ProjectId -cne $projectId) { throw 'Power plan project ID mismatch.' }",
  "  if ($State.ActionId -cne $Entry.Id) { throw 'Power plan action ID mismatch.' }",
  "  if ($State.ActionKind -cne 'power-plan') { throw 'Power plan action kind mismatch.' }",
  "  if ($State.TargetGuid -cne $Entry.SchemeGuid) { throw 'Power plan target mismatch.' }",
  "  $guidPattern = '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'",
  "  if ($State.TargetGuid -cnotmatch $guidPattern -or $State.ActiveGuid -cnotmatch $guidPattern) { throw 'Power plan state GUID is invalid.' }",
  "}",
  "function Read-PowerPlanState([string]$Path, [object]$Entry) {",
  "  $file = Get-Item -LiteralPath $Path",
  "  if ($file.Length -gt 1048576) { throw 'Power plan state is too large.' }",
  "  $state = Import-Clixml -LiteralPath $Path",
  "  Assert-PowerPlanState $state $Entry",
  "  return $state",
  "}",
  "function Get-PowerCfgPath {",
  "  $path = Join-Path ([Environment]::SystemDirectory) 'powercfg.exe'",
  "  if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { throw 'powercfg.exe was not found in System32.' }",
  "  return $path",
  "}",
  "function Invoke-PowerCfg([string[]]$Arguments) {",
  "  $powercfg = Get-PowerCfgPath",
  "  $output = @(& $powercfg @Arguments 2>&1)",
  "  $exitCode = $LASTEXITCODE",
  "  if ($exitCode -ne 0) { throw ('powercfg.exe failed with exit code ' + $exitCode + ': ' + ($output -join ' ')) }",
  "  return [string[]]$output",
  "}",
  "function Get-ActivePowerPlanGuid {",
  "  $output = Invoke-PowerCfg @('/getactivescheme')",
  "  $text = $output -join \"`n\"",
  "  $guidPattern = '(?i)\\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\\b'",
  "  $guids = @([regex]::Matches($text, $guidPattern) | ForEach-Object { $_.Value.ToLowerInvariant() } | Select-Object -Unique)",
  "  if ($guids.Count -ne 1) { throw 'The active power plan GUID could not be determined.' }",
  "  return [string]$guids[0]",
  "}",
  "function Save-PowerPlanState([object]$Entry, [string]$Path) {",
  "  $temporary = $Path + '.' + $PID + '.tmp'",
  "  try {",
  "    $activeGuid = Get-ActivePowerPlanGuid",
  "    $state = [pscustomobject]@{ Schema=2; ProjectId=$projectId; ActionId=$Entry.Id; ActionKind='power-plan'; TargetGuid=$Entry.SchemeGuid; ActiveGuid=$activeGuid }",
  "    $state | Export-Clixml -LiteralPath $temporary -Depth 3",
  "    [void](Read-PowerPlanState $temporary $Entry)",
  "    Move-Item -LiteralPath $temporary -Destination $Path -Force",
  "  } finally {",
  "    if (Test-Path -LiteralPath $temporary) { Remove-Item -LiteralPath $temporary -Force -ErrorAction SilentlyContinue }",
  "  }",
  "}",
  "function Apply-PowerPlan([object]$Entry) {",
  "  $mutex = [Threading.Mutex]::new($false, ('Local\\GamingTweakForge_' + $projectId + '_' + $Entry.Id))",
  "  $lockTaken = $false",
  "  try {",
  "    try { $lockTaken = $mutex.WaitOne(30000) } catch [Threading.AbandonedMutexException] { $lockTaken = $true }",
  "    if (-not $lockTaken) { throw 'Timed out waiting for another power plan action.' }",
  "    $stateFile = Join-Path $stateRoot ($Entry.Id + '.clixml')",
  "    if (Test-Path -LiteralPath $stateFile) { [void](Read-PowerPlanState $stateFile $Entry) } else { Save-PowerPlanState $Entry $stateFile }",
  "    [void](Invoke-PowerCfg @('/setactive', $Entry.SchemeGuid))",
  "  } finally {",
  "    if ($lockTaken) { [void]$mutex.ReleaseMutex() }",
  "    $mutex.Dispose()",
  "  }",
  "}",
  "function Restore-PowerPlan([object]$Entry) {",
  "  $mutex = [Threading.Mutex]::new($false, ('Local\\GamingTweakForge_' + $projectId + '_' + $Entry.Id))",
  "  $lockTaken = $false",
  "  try {",
  "    try { $lockTaken = $mutex.WaitOne(30000) } catch [Threading.AbandonedMutexException] { $lockTaken = $true }",
  "    if (-not $lockTaken) { throw 'Timed out waiting for another power plan action.' }",
  "    $stateFile = Join-Path $stateRoot ($Entry.Id + '.clixml')",
  "    if (-not (Test-Path -LiteralPath $stateFile)) { Write-Result $Entry.Id 'Restore' 'NO_BACKUP'; return }",
  "    $state = Read-PowerPlanState $stateFile $Entry",
  "    [void](Invoke-PowerCfg @('/setactive', $state.ActiveGuid))",
  "    Remove-Item -LiteralPath $stateFile -Force",
  "  } finally {",
  "    if ($lockTaken) { [void]$mutex.ReleaseMutex() }",
  "    $mutex.Dispose()",
  "  }",
  "}",
] as const;
