export function buildProtectedDirectoryFunctions(): readonly string[] {
  return [
    "function New-ProtectedDirectorySecurity {",
    "  $administrators = [Security.Principal.SecurityIdentifier]::new([Security.Principal.WellKnownSidType]::BuiltinAdministratorsSid, $null)",
    "  $system = [Security.Principal.SecurityIdentifier]::new([Security.Principal.WellKnownSidType]::LocalSystemSid, $null)",
    "  $inheritance = [Security.AccessControl.InheritanceFlags]::ContainerInherit -bor [Security.AccessControl.InheritanceFlags]::ObjectInherit",
    "  $propagation = [Security.AccessControl.PropagationFlags]::None",
    "  $allow = [Security.AccessControl.AccessControlType]::Allow",
    "  $security = [Security.AccessControl.DirectorySecurity]::new()",
    "  $security.SetAccessRuleProtection($true, $false)",
    "  $security.SetOwner($administrators)",
    "  [void]$security.AddAccessRule([Security.AccessControl.FileSystemAccessRule]::new($administrators, [Security.AccessControl.FileSystemRights]::FullControl, $inheritance, $propagation, $allow))",
    "  [void]$security.AddAccessRule([Security.AccessControl.FileSystemAccessRule]::new($system, [Security.AccessControl.FileSystemRights]::FullControl, $inheritance, $propagation, $allow))",
    "  return $security",
    "}",
    "function Test-ProtectedDirectory([string]$Path) {",
    "  if (-not (Test-Path -LiteralPath $Path -PathType Container)) { return $false }",
    "  $item = Get-Item -LiteralPath $Path -Force",
    "  if (($item.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) { return $false }",
    "  $administrators = [Security.Principal.SecurityIdentifier]::new([Security.Principal.WellKnownSidType]::BuiltinAdministratorsSid, $null)",
    "  $system = [Security.Principal.SecurityIdentifier]::new([Security.Principal.WellKnownSidType]::LocalSystemSid, $null)",
    "  $security = [IO.Directory]::GetAccessControl($Path)",
    "  if (-not $security.AreAccessRulesProtected) { return $false }",
    "  if ($security.GetOwner([Security.Principal.SecurityIdentifier]).Value -cne $administrators.Value) { return $false }",
    "  $rules = @($security.GetAccessRules($true, $false, [Security.Principal.SecurityIdentifier]))",
    "  if ($rules.Count -ne 2) { return $false }",
    "  $expected = @($administrators.Value, $system.Value)",
    "  $observed = @()",
    "  foreach ($rule in $rules) {",
    "    $identity = $rule.IdentityReference.Value",
    "    if ($expected -cnotcontains $identity) { return $false }",
    "    if ($rule.AccessControlType -ne [Security.AccessControl.AccessControlType]::Allow) { return $false }",
    "    if ($rule.FileSystemRights -ne [Security.AccessControl.FileSystemRights]::FullControl) { return $false }",
    "    if ($rule.InheritanceFlags -ne ([Security.AccessControl.InheritanceFlags]::ContainerInherit -bor [Security.AccessControl.InheritanceFlags]::ObjectInherit)) { return $false }",
    "    if ($rule.PropagationFlags -ne [Security.AccessControl.PropagationFlags]::None -or $rule.IsInherited) { return $false }",
    "    $observed += $identity",
    "  }",
    "  foreach ($identity in $expected) { if ($observed -cnotcontains $identity) { return $false } }",
    "  return $true",
    "}",
    "function Open-ProtectedDirectory([string]$Path) {",
    "  if (-not (Test-Path -LiteralPath $Path)) {",
    "    $security = New-ProtectedDirectorySecurity",
    "    [void][IO.Directory]::CreateDirectory($Path, $security)",
    "  }",
    "  if (-not (Test-ProtectedDirectory $Path)) { throw ('Protected directory is not trusted: ' + $Path) }",
    "}",
  ];
}
